import OpportunityBoard from '@/components/opportunity-board';

export default function Home(){
 return <main>
  <section className="hero"><div className="container"><nav className="nav"><div className="logo">imkon<span>.</span></div><div className="nav-actions"><a href="#opportunities">Imkoniyatlar</a><a className="profile-btn" href="/profile">Mening profilim</a></div></nav><div className="hero-grid"><div><div className="pill">✦ O‘zbekiston yoshlari uchun</div><div className="eyebrow" style={{marginTop:22}}>SIZGA MOS IMKONIYATLAR — BIR JOYDA</div><h1>Yaxshi imkoniyatni qidirib <span style={{color:'var(--accent)'}}>vaqt yo‘qotmang.</span></h1><p className="hero-copy">Hududingiz, yo‘nalishingiz va tajribangizga mos ish, stajirovka, grant va bepul kurslarni bir joydan toping.</p><div className="actions"><a className="btn btn-primary" href="#opportunities">Menga moslarini topish →</a><a className="btn btn-secondary" href="#how">Qanday ishlaydi?</a></div></div><div className="mock"><div className="phone"><div className="phone-top"><span>IMKON</span><span>● ● ●</span></div><div className="bot-title">Salom 👋</div><div className="bot-sub">Real manbalardan saralangan imkoniyatlar.</div><div className="op"><strong>Machine Learning</strong><small>Remote · Real-time qidiruv</small><span className="tag">Ish</span><span className="tag">Manba ko‘rsatilgan</span></div><div className="op"><strong>Student Internship</strong><small>O‘zbekiston · Ofis</small><span className="tag">Stajirovka</span></div><div className="op"><strong>Free Skills Program</strong><small>Masofaviy</small><span className="tag">Kurs</span></div></div></div></div></div></section>
  <section className="section" id="how"><div className="container"><div className="section-head"><div className="eyebrow">3 QADAM</div><h2>Telegramdagi shovqinni foydali imkoniyatga aylantiramiz.</h2><p className="muted">Imkon bazadagi e’lonlar va ruxsat etilgan ochiq manbalardan natijalarni yig‘ib, ularni profilingizga moslab tartiblaydi.</p></div><div className="grid3"><div className="card"><div className="number">01</div><h3>Profilingizni belgilang</h3><p className="muted">Hudud, yo‘nalish, tajriba va formatni tanlang.</p></div><div className="card"><div className="number">02</div><h3>Real manbalardan qidiring</h3><p className="muted">ML, Python yoki SMM kabi so‘zlar bo‘yicha kengaytirilgan qidiruv ishlaydi.</p></div><div className="card"><div className="number">03</div><h3>Saqlang va murojaat qiling</h3><p className="muted">Manba va rasmiy havola har bir tashqi e’lon bilan birga ko‘rsatiladi.</p></div></div></div></section>
  <OpportunityBoard />
  <section className="section"><div className="container"><div className="cta"><div><div className="eyebrow" style={{color:'#8de2bf'}}>IMKONNI O‘TKAZIB YUBORMANG</div><h2>Keyingi yaxshi imkoniyat<br/>sizniki bo‘lishi mumkin.</h2></div><a className="btn" style={{background:'#fff',color:'var(--ink)'}} href="#opportunities">Boshlash →</a></div></div></section><footer><div className="container">© 2026 Imkon · Yaxshi imkoniyatlar hammaga yaqin.</div></footer>
 </main>;
}
