'use client';

import { useEffect, useMemo, useState } from 'react';

type Opportunity = { id:string; title:string; organization:string; type:'Ish'|'Stajirovka'|'Grant'|'Kurs'; location:string; mode:'Masofaviy'|'Ofis'|'Gibrid'; category:string; experience:string; description:string; deadline:string|null; url:string; is_verified:boolean };
type Profile = { location:string; category:string; experience:string; mode:string; type:string };
const demo:Opportunity[]=[{id:'1',title:'Junior SMM Assistant',organization:'Local startup',type:'Ish',location:'Toshkent',mode:'Gibrid',category:'SMM',experience:'Boshlang‘ich',description:'Kontent rejalashtirish va ijtimoiy tarmoqlar bilan ishlash.',deadline:null,url:'',is_verified:true},{id:'2',title:'Frontend Internship',organization:'Tech company',type:'Stajirovka',location:'Toshkent',mode:'Ofis',category:'IT',experience:'Boshlang‘ich',description:'Real product jamoasida frontend tajribasi olish imkoniyati.',deadline:null,url:'',is_verified:true},{id:'3',title:'Digital Skills Scholarship',organization:'Education foundation',type:'Grant',location:'O‘zbekiston',mode:'Masofaviy',category:'Ta’lim',experience:'Boshlang‘ich',description:'Raqamli ko‘nikmalar kurslari uchun to‘liq grant.',deadline:null,url:'',is_verified:true},{id:'4',title:'English for Career — Free',organization:'Open learning',type:'Kurs',location:'O‘zbekiston',mode:'Masofaviy',category:'Ingliz tili',experience:'Boshlang‘ich',description:'Ish va universitet uchun bepul ingliz tili kursi.',deadline:null,url:'',is_verified:true}];
const types=['Barchasi','Ish','Stajirovka','Grant','Kurs'];
const emptyProfile:Profile={location:'',category:'',experience:'',mode:'',type:''};
const aliases:Record<string,string[]>={ml:['ml','machine learning','sun’iy intellekt','suniy intellekt','ai','data science','data scientist','machine'],ai:['ai','sun’iy intellekt','suniy intellekt','machine learning','ml'],data:['data','data science','data analyst','machine learning','ml'],frontend:['frontend','front-end','web development','react','next.js'],backend:['backend','back-end','node.js','python','api'],it:['it','software','dastur','program','frontend','backend','data','ai','ml']};
const terms=(value:string)=>{const v=value.trim().toLowerCase();return [v,...(aliases[v]||[])].filter(Boolean)};

export default function Home(){
 const [items,setItems]=useState<Opportunity[]>(demo),[type,setType]=useState('Barchasi'),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[profile,setProfile]=useState<Profile>(emptyProfile),[onboard,setOnboard]=useState(false),[saved,setSaved]=useState<string[]>([]);
 useEffect(()=>{fetch('/api/opportunities').then(r=>r.json()).then(d=>{if(Array.isArray(d.opportunities)&&d.opportunities.length)setItems(d.opportunities)}).catch(()=>{}).finally(()=>setLoading(false));try{const p=localStorage.getItem('imkon-profile');if(p)setProfile(JSON.parse(p));const s=localStorage.getItem('imkon-saved');if(s)setSaved(JSON.parse(s));}catch{}},[]);
 const save=(id:string)=>setSaved(x=>{const n=x.includes(id)?x.filter(i=>i!==id):[...x,id];localStorage.setItem('imkon-saved',JSON.stringify(n));return n});
 const score=(o:Opportunity)=>{let s=0;const cats=terms(profile.category);const text=`${o.title} ${o.category} ${o.description}`.toLowerCase();if(profile.location&&o.location.toLowerCase().includes(profile.location.toLowerCase()))s+=3;if(profile.category&&(cats.some(t=>o.category.toLowerCase().includes(t))||cats.some(t=>text.includes(t))))s+=5;if(profile.experience&&o.experience===profile.experience)s+=2;if(profile.mode&&o.mode===profile.mode)s+=2;if(profile.type&&profile.type!=='Barchasi'&&o.type===profile.type)s+=2;return s};
 const filtered=useMemo(()=>items.filter(o=>(type==='Barchasi'||o.type===type)&&`${o.title} ${o.organization} ${o.category} ${o.location} ${o.description}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>score(b)-score(a)),[items,type,query,profile]);
 const submitProfile=()=>{localStorage.setItem('imkon-profile',JSON.stringify(profile));setOnboard(false);document.getElementById('opportunities')?.scrollIntoView({behavior:'smooth'})};
 return <main>
  {onboard&&<div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={()=>setOnboard(false)}>×</button><div className="eyebrow">SIZGA MOSLASH</div><h2>30 soniyada boshlang.</h2><p className="muted">Profilingizni belgilang — Imkon natijalarni sizga mosroq tartiblaydi.</p><div className="form-grid"><input placeholder="Hudud: masalan Qarshi" value={profile.location} onChange={e=>setProfile({...profile,location:e.target.value})}/><input placeholder="Yo‘nalish: IT, SMM, ML..." value={profile.category} onChange={e=>setProfile({...profile,category:e.target.value})}/><select value={profile.experience} onChange={e=>setProfile({...profile,experience:e.target.value})}><option value="">Tajriba</option><option>Boshlang‘ich</option><option>O‘rta</option><option>Tajribali</option></select><select value={profile.mode} onChange={e=>setProfile({...profile,mode:e.target.value})}><option value="">Format</option><option>Masofaviy</option><option>Ofis</option><option>Gibrid</option></select><select value={profile.type} onChange={e=>setProfile({...profile,type:e.target.value})}><option>Barchasi</option><option>Ish</option><option>Stajirovka</option><option>Grant</option><option>Kurs</option></select></div><button className="btn btn-primary full" onClick={submitProfile}>Mos imkoniyatlarni topish →</button></div></div>}
  <section className="hero"><div className="container"><nav className="nav"><div className="logo">imkon<span>.</span></div><div className="nav-actions"><a href="#opportunities">Imkoniyatlar</a><button className="profile-btn" onClick={()=>setOnboard(true)}>Mening profilim</button></div></nav><div className="hero-grid"><div><div className="pill">✦ O‘zbekiston yoshlari uchun</div><div className="eyebrow" style={{marginTop:22}}>SIZGA MOS IMKONIYATLAR — BIR JOYDA</div><h1>Yaxshi imkoniyatni qidirib <span style={{color:'var(--accent)'}}>vaqt yo‘qotmang.</span></h1><p className="hero-copy">Hududingiz, yo‘nalishingiz va tajribangizga mos ish, stajirovka, grant va bepul kurslarni bir joydan toping.</p><div className="actions"><button className="btn btn-primary" onClick={()=>setOnboard(true)}>Menga moslarini topish →</button><a className="btn btn-secondary" href="#how">Qanday ishlaydi?</a></div></div><div className="mock"><div className="phone"><div className="phone-top"><span>IMKON</span><span>● ● ●</span></div><div className="bot-title">Salom 👋</div><div className="bot-sub">Siz uchun saralangan imkoniyatlar.</div>{filtered.slice(0,3).map(o=><div className="op" key={o.id}><strong>{o.title}</strong><small>{o.location} · {o.mode}</small><span className="tag">{o.type}</span>{o.is_verified&&<span className="tag">✓ Tekshirilgan</span>}</div>)}</div></div></div></div></section>
  <section className="section" id="how"><div className="container"><div className="section-head"><div className="eyebrow">3 QADAM</div><h2>Telegramdagi shovqinni foydali imkoniyatga aylantiramiz.</h2><p className="muted">Yuzlab kanallarni kuzatish shart emas. Imkon kerakli imkoniyatlarni bir joyga jamlaydi.</p></div><div className="grid3"><div className="card"><div className="number">01</div><h3>Profilingizni belgilang</h3><p className="muted">Hudud, yo‘nalish, tajriba va formatni tanlang.</p></div><div className="card"><div className="number">02</div><h3>Moslarini toping</h3><p className="muted">Natijalar profilingizga mosligi bo‘yicha tartiblanadi.</p></div><div className="card"><div className="number">03</div><h3>Saqlab qo‘ying</h3><p className="muted">Qiziqqan imkoniyatlaringizni bir joyda saqlang.</p></div></div></div></section>
  <section className="section" id="opportunities" style={{paddingTop:20}}><div className="container"><div className="section-head"><div className="eyebrow">IMKONIYATLAR</div><h2>Hozir sizga mos bo‘lishi mumkin.</h2><p className="muted">Qidiring, filtrlang va moslarini saqlang.</p></div><div className="filters"><input aria-label="Qidirish" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Masalan: SMM, IT, Toshkent..."/><div className="filter-tabs">{types.map(t=><button key={t} className={type===t?'active':''} onClick={()=>setType(t)}>{t}</button>)}</div></div>{loading&&<p className="muted">Imkoniyatlar yuklanmoqda...</p>}<div className="opps">{filtered.map(o=><article className="opportunity" key={o.id}><div className="type">{o.type.toUpperCase()} {o.is_verified&&' · ✓ TEKSHIRILGAN'}</div><h3>{o.title}</h3><div className="meta">{o.organization} · {o.location} · {o.mode}<br/>{o.category} · {o.experience}</div><p className="muted">{o.description}</p><div className="card-actions"><a className="card-link" href={`/opportunities/${o.id}`}>Batafsil →</a><button className={`save-btn ${saved.includes(o.id)?'saved':''}`} onClick={()=>save(o.id)}>{saved.includes(o.id)?'♥ Saqlandi':'♡ Saqlash'}</button></div></article>)}</div>{!loading&&!filtered.length&&<div className="empty"><strong>Hozircha mos imkoniyat topilmadi.</strong><p className="muted">Qidiruv yoki filtrni o‘zgartirib ko‘ring.</p></div>}</div></section>
  <section className="section"><div className="container"><div className="cta"><div><div className="eyebrow" style={{color:'#8de2bf'}}>IMKONNI O‘TKAZIB YUBORMANG</div><h2>Keyingi yaxshi imkoniyat<br/>sizniki bo‘lishi mumkin.</h2></div><button className="btn" style={{background:'#fff',color:'var(--ink)'}} onClick={()=>setOnboard(true)}>Boshlash →</button></div></div></section><footer><div className="container">© 2026 Imkon · Yaxshi imkoniyatlar hammaga yaqin.</div></footer>
 </main>
}